In [13]:
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt

In [14]:
# Load the dataset
df = pd.read_excel('aggregati_1.xlsx')

# Display the first few rows of the dataframe
display(df.head())

,Unnamed: 0,ANNO,NUMERO,VOLUME,PESO,COMMITTENTE,LINEA,QUANTITA_IMBALLI,VIAGGIO_RITIRO_NUMERO,CODICE_DESTINATARIO,...,CODICE MITTENTE,Ragione_Sociale_MITTENTE,INDIRIZZO_mittente,CAP_mittente,LOCALITA_mittente,PROVINCIA_mittente,NAZIONE_mittente,lat_mittente,lon_mittente,QUANTITA
0,0,2025,1,2.420,1072.0,2435,VET,2,NaN,118499,...,101112,magazino festa m6,"via levate, 62",25018,montichiari,bs,it,45.435798,10.356909,2.0
1,1,2025,2,57.024,0.0,1548,TRA,33,33483.0,98348,...,67921,bricoman italia srl rivaltalogistic,"strada comunale savonesa, 12",15057,rivalta scrivia,al,it,0.000000,0.000000,33.0
2,2,2025,3,57.024,0.0,2430,TRA,33,33432.0,3852,...,60414,cliente imola,0,40026,imola,bo,it,44.362693,11.709072,33.0
3,3,2025,4,57.024,0.0,2430,TRA,33,33484.0,3852,...,60414,cliente imola,0,40026,imola,bo,it,44.362693,11.709072,33.0
4,4,2025,5,0.000,0.0,2543,TRA,12,NaN,104870,...,90892,magazzino festa m12,"via levate, 58",25018,montichiari,bs,it,45.435668,10.357449,12.0

In [15]:
print(df.columns)

Index(['Unnamed: 0', 'ANNO', 'NUMERO', 'VOLUME', 'PESO', 'COMMITTENTE',
       'LINEA', 'QUANTITA_IMBALLI', 'VIAGGIO_RITIRO_NUMERO',
       'CODICE_DESTINATARIO', 'RAGIONE_SOCIALE_destinatario',
       'INDIRIZZO_destinatario', 'CAP_destinatario', 'LOCALITA_destinatario',
       'PROVINCIA_destinatario', 'NAZIONE_destinatario', 'lat_destinatario',
       'lon_destinatario', 'CODICE MITTENTE', 'Ragione_Sociale_MITTENTE',
       'INDIRIZZO_mittente', 'CAP_mittente', 'LOCALITA_mittente',
       'PROVINCIA_mittente', 'NAZIONE_mittente', 'lat_mittente',
       'lon_mittente', 'QUANTITA'],
      dtype='object')

In [16]:
# Dictionary to translate column names
translation_dict = {
    'Unnamed: 0': 'Index',
    'ANNO': 'Year',
    'NUMERO': 'Delivery_Number',
    'VOLUME': 'Volume',
    'PESO': 'Weight',
    'COMMITTENTE': 'Client',
    'LINEA': 'Delivery_Line',
    'QUANTITA_IMBALLI': 'Package_Quantity',
    'VIAGGIO_RITIRO_NUMERO': 'Pickup_Trip_Number',
    'CODICE_DESTINATARIO': 'Recipient_Code',
    'RAGIONE_SOCIALE_destinatario': 'Recipient_Company_Name',
    'INDIRIZZO_destinatario': 'Recipient_Address',
    'CAP_destinatario': 'Recipient_Zip_Code',
    'LOCALITA_destinatario': 'Recipient_City',
    'PROVINCIA_destinatario': 'Recipient_Province',
    'NAZIONE_destinatario': 'Recipient_Country',
    'lat_destinatario': 'Recipient_Latitude',
    'lon_destinatario': 'Recipient_Longitude',
    'CODICE MITTENTE': 'Sender_Code',
    'Ragione_Sociale_MITTENTE': 'Sender_Company_Name',
    'INDIRIZZO_mittente': 'Sender_Address',
    'CAP_mittente': 'Sender_Zip_Code',
    'LOCALITA_mittente': 'Sender_City',
    'PROVINCIA_mittente': 'Sender_Province',
    'NAZIONE_mittente': 'Sender_Country',
    'lat_mittente': 'Sender_Latitude',
    'lon_mittente': 'Sender_Longitude',
    'QUANTITA': 'Quantity'
}

# Rename columns
df.rename(columns=translation_dict, inplace=True)

# Display the first few rows of the dataframe to verify the changes
display(df.head())

,Index,Year,Delivery_Number,Volume,Weight,Client,Delivery_Line,Package_Quantity,Pickup_Trip_Number,Recipient_Code,...,Sender_Code,Sender_Company_Name,Sender_Address,Sender_Zip_Code,Sender_City,Sender_Province,Sender_Country,Sender_Latitude,Sender_Longitude,Quantity
0,0,2025,1,2.420,1072.0,2435,VET,2,NaN,118499,...,101112,magazino festa m6,"via levate, 62",25018,montichiari,bs,it,45.435798,10.356909,2.0
1,1,2025,2,57.024,0.0,1548,TRA,33,33483.0,98348,...,67921,bricoman italia srl rivaltalogistic,"strada comunale savonesa, 12",15057,rivalta scrivia,al,it,0.000000,0.000000,33.0
2,2,2025,3,57.024,0.0,2430,TRA,33,33432.0,3852,...,60414,cliente imola,0,40026,imola,bo,it,44.362693,11.709072,33.0
3,3,2025,4,57.024,0.0,2430,TRA,33,33484.0,3852,...,60414,cliente imola,0,40026,imola,bo,it,44.362693,11.709072,33.0
4,4,2025,5,0.000,0.0,2543,TRA,12,NaN,104870,...,90892,magazzino festa m12,"via levate, 58",25018,montichiari,bs,it,45.435668,10.357449,12.0

In [17]:
df.drop(columns=['Quantity'], inplace=True)

# Display the first few rows of the dataframe to verify the changes
display(df.head())

,Index,Year,Delivery_Number,Volume,Weight,Client,Delivery_Line,Package_Quantity,Pickup_Trip_Number,Recipient_Code,...,Recipient_Longitude,Sender_Code,Sender_Company_Name,Sender_Address,Sender_Zip_Code,Sender_City,Sender_Province,Sender_Country,Sender_Latitude,Sender_Longitude
0,0,2025,1,2.420,1072.0,2435,VET,2,NaN,118499,...,0.000000,101112,magazino festa m6,"via levate, 62",25018,montichiari,bs,it,45.435798,10.356909
1,1,2025,2,57.024,0.0,1548,TRA,33,33483.0,98348,...,0.000000,67921,bricoman italia srl rivaltalogistic,"strada comunale savonesa, 12",15057,rivalta scrivia,al,it,0.000000,0.000000
2,2,2025,3,57.024,0.0,2430,TRA,33,33432.0,3852,...,0.000000,60414,cliente imola,0,40026,imola,bo,it,44.362693,11.709072
3,3,2025,4,57.024,0.0,2430,TRA,33,33484.0,3852,...,0.000000,60414,cliente imola,0,40026,imola,bo,it,44.362693,11.709072
4,4,2025,5,0.000,0.0,2543,TRA,12,NaN,104870,...,10.306816,90892,magazzino festa m12,"via levate, 58",25018,montichiari,bs,it,45.435668,10.357449

In [ ]:
from sklearn.model_selection import train_test_split

# Split the dataset into train (60%), evaluation (20%), and test (20%) sets
train_df, temp_df = train_test_split(df, test_size=0.4, random_state=42)
eval_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

# Define the features (X) and target (y) for each set
X_train = train_df[['Volume']]
y_train = train_df['Weight']
X_eval = eval_df[['Volume']]
y_eval = eval_df['Weight']
X_test = test_df[['Volume']]
y_test = test_df['Weight']

# Display the number of rows in each set
print(f"Train set: {train_df.shape[0]} rows")
print(f"Evaluation set: {eval_df.shape[0]} rows")
print(f"Test set: {test_df.shape[0]} rows")

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Define the features (X) and target (y)
X = df[['Volume']]  # Assuming 'Volume' is the feature for regression
y = df['Weight']

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate and print the mean squared error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Plot the results
plt.scatter(X_test, y_test, color='black', label='Actual')
plt.plot(X_test, y_pred, color='blue', linewidth=3, label='Predicted')
plt.xlabel('Volume')
plt.ylabel('Weight')
plt.legend()
plt.show()

NameError: name 'X_train' is not defined